### ISSUE TITLE
Which host files are these hosts pulled from?

### ISSUE THREAD

**Issue by T145** [hemiipatu/PiHoleBlocklists#16]
You reference in the README that the list entries are from other lists, but don't credit those other lists. Is that information available?

**Comment by hemiipatu** [comment]
Hi @T145. Please accept my apologies for the delayed response - I've been inundated with real life and haven't had the time to do anything with my hobbies.

You're correct. This list is curated from a number of others but I haven't as yet given credit! I'll add this within the next seven days.
