### ISSUE TITLE
assets-jpcust.jwpsrv.com videos-fms.jwpsrv.com

### ISSUE THREAD

**Issue by p1r473** [hemiipatu/PiHoleBlocklists#8]
These domains block embedded videos
Here is an example of the embedded video i could not play
https://forums.androidcentral.com/droid-bionic/130214-battery-symbol-question-mark-inside.html

**Comment by hemiipatu** [comment]
This is one of those strange domains that serve both advertisements and legitimate videos. I could remove it from the blocklist(s) but it would mean some adverts could still be passed.

Might be worth me making an additional lists that people can choose which are more restrictive for instances such as these.

What are your thoughts?

**Comment by p1r473** [comment]
Can you confirm that these serve ads?
Out of my [500 blocklists](https://raw.githubusercontent.com/p1r473/hosts/master/adlists.txt) only 2 have these blocked

I always whitelist on my end; even if you supplied a more cleaned up list to use, I'd still use the bigger one and whitelist on my end :)

My personal thoughts are that if anyone is using this list, they may be annoyed at the video they try to watch is not available to them

**Comment by hemiipatu** [comment]
I can confirm that the domain does indeed serve advertisements, however it's a rare occurrence and I'd argue that it's so rare an occasion that I will indeed just remove it and only include it in the more comprehensive list.

In the coming weeks during my days off work I will start updating the lists and create some new options for people to pick that're more or less aggressive.
